### ISSUE TITLE
Vagrant up fails

### ISSUE THREAD

**Issue by nvanderperren** [VlaamseKunstcollectie/Imagehub-Box#3] opened 2019-04-30 09:19 UTC
I followed the instructions in the README. I encountered this issue after doing `vagrant up`:

```console
MacBook-Pro-van-Nastasia:Imagehub-Box nastasia$ vagrant up
$Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/nastasia/Developer/Imagehub-Box/Vagrantfile
Line number: 0
Message: Psych::SyntaxError: (/Users/nastasia/Developer/Imagehub-Box/config.yml): did not find expected key while parsing a block mapping at line 3 column 1
MacBook-Pro-van-Nastasia:Imagehub-Box nastasia$ 
```

Any thoughts?

**Comment by Hobbesball** [comment] 2019-04-30 10:18
Hm, it's possible the syntax got a bit muddled while you were entering the path to your vagrant synced folder. Can you share that part of your config.yml file with me? Mine looks like this:

```
# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders:
  # The first synced folder will be used for the default Imagehub installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the imagehub folder.
  - local_path: /Users/jolanwuyts/Workspace/datahub
    destination: /vagrant
    type: nfs
create: true
```

Your issue might be one of [this type](https://github.com/ruby/psych/issues/190)

**Comment by nvanderperren** [comment] 2019-04-30 10:28
my config.yml file:

```yml
---

vagrant_box: imagehub-bionic64
vagrant_box_url: file://packer/build/imagehub-bionic64.box

vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# If you need to run multiple instances of Imagehub Box VM,
# set a unique hostname, machine name, and IP address for 
# each instance.
vagrant_hostname: imagehub.box
vagrant_machine_name: imagehubbox
vagrant_ip: 192.168.2.152

# Allow Imagehub Box VM to be accessed via a public network
# Allow Imagehub Box VM to be accessed via a public network
# interface on your host. Vagrant boxes are insecure by default, 
# so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""


# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders: /Users/nastasia/Projects
  # The first synced folder will be used for the default Imagehub installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the imagehub folder.
  - local_path: .
    destination: /vagrant
    type: nfs
create: true

# Memory and CPU to use for this VM.
vagrant_memory: 5120
vagrant_cpus: 1

# Ensure vagrant plugins are installed.
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater

# Minimum required versions.
imagehubbox_vagrant_version_min: '1.8.6'

# Domain names
datahub_domain: datahub.box
blacklight_domain: blacklight.box
dashboard_domain: dashboard.box
imagehub_domain: imagehub.box
cantaloupe_domain: cantaloupe.box
resourcespace_domain: resourcespace.box

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. 
nginx_hosts:
  - server_name: "{{ datahub_domain }} www.{{ datahub_domain }}"
  - server_name: "{{ blacklight_domain }} www.{{ blacklight_domain }}"
  - server_name: "{{ dashboard_domain }} www.{{ dashboard_domain }}"
  - server_name: "{{ imagehub_domain }} www.{{ imagehub_domain }}"
  - server_name: "{{ cantaloupe_domain }} www.{{ cantaloupe_domain }}"
  - server_name: "{{ resourcespace_domain }} www.{{ resourcespace_domain }}"
```

**Comment by nvanderperren** [comment] 2019-04-30 10:29
Oh, I see my mistake now.

**Comment by nvanderperren** [comment] 2019-04-30 10:31
everything seems to work fine now 🙄 Sorry!

**Comment by nvanderperren** [comment] 2019-04-30 10:34
That was the mistake 🙄 . But now I need to enter a password?

```console
==> imagehub.box: Pruning invalid NFS exports. Administrator privileges will be required...
Password:
Sorry, try again.
Password:
```

**Comment by Hobbesball** [comment] 2019-04-30 10:36
glad that got fixed! You need to enter the administrator password of your computer to give the box the privileges it needs :)

**Comment by nvanderperren** [comment] 2019-04-30 10:46
Now this

```console
==> imagehub.box: Machine booted and ready!
[imagehub.box] GuestAdditions versions on your host (5.2.16) and guest (5.2.8) do not match.
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Hit:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
==> imagehub.box: Checking for guest additions in VM...
==> imagehub.box: [vagrant-hostsupdater] Checking for host entries
==> imagehub.box: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  imagehub.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  datahub.box www.datahub.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  blacklight.box www.blacklight.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  dashboard.box www.dashboard.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  imagehub.box www.imagehub.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  cantaloupe.box www.cantaloupe.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater]   192.168.2.152  resourcespace.box www.resourcespace.box  # VAGRANT: a9bb0c961abb09a49ec07aadf830dd58 (imagehub.box) / 5760f99e-9892-4402-bfd4-35be3ef723b4
==> imagehub.box: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:



Stderr from the command:

E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

**Comment by nvanderperren** [comment] 2019-04-30 10:52
`vagrant halt` and then again `vagrant up` solved the issue.

**Comment by Hobbesball** [comment] 2019-04-30 12:12
Thanks for the followup! Glad to hear that the issue was solved.

@netsensei I believe we can get rid of the dpkg lock issue by implementing [this fix](https://github.com/hashicorp/vagrant/issues/7508#issuecomment-281332526) in vagrant.configure in the Vagrantfile. It should prevent dpkg from locking up while provisioning a box with vagrant when another process is using apt or a lock file is generated.  Does this seem like a good idea to you? I've ran into the dpkg lock issue once or twice as well, it's a bit annoying, but is most often fixed by `vagrant halt&&vagrant up`.

**Comment by netsensei** [comment] 2019-05-11 22:36
So, apt is configured to trigger periodic automatic updates (unattended). This causes problems with locking. The fix above tries to skirt around this in a hacky way if you download and use a box from Vagrant Cloud. 

We are building our own boxes from scratches via Packer, so we can fix the root cause of the problem. 

See: https://github.com/geerlingguy/packer-ubuntu-1604/issues/7

The fix is in this commit: https://github.com/geerlingguy/packer-ubuntu-1604/commit/0bcad82234c38b6de792b76660e8cfd14826973b

**Comment by Hobbesball** [comment] 2019-05-13 10:05
Thanks! Closing this issue, fixing the dpkg lockup issue will be handled in https://github.com/thedatahub/Datahub-Box/issues/11

**Closed as completed by Hobbesball** 2019-05-13 10:05 UTC
